In [46]:
import tensorflow as tf
import torch as torch
from tensorflow.keras.models import Sequential
import pandas as pd
import numpy as np
from numpy import array
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import LSTM
from sklearn.metrics import mean_squared_error
from math import sqrt
import matplotlib.pyplot as plt

In [8]:
data = pd.read_csv("~/PycharmProjects/Diabetes/final.csv", sep=',')

Albumin_Creatinine_data = data[['Patient_ID', 'PerformedDate', 'Albumin/Creatinine_Res']]
Albumin_Creatinine_data = Albumin_Creatinine_data.dropna()
Albumin_Creatinine_data = Albumin_Creatinine_data[Albumin_Creatinine_data['Albumin/Creatinine_Res'] < 300]
Albumin_Creatinine_data = Albumin_Creatinine_data.sort_values(by='PerformedDate', ascending=True)

grouped_patients = Albumin_Creatinine_data.groupby("Patient_ID")
grouped_lists = grouped_patients["Albumin/Creatinine_Res"].apply(list)
grouped_lists = grouped_lists.reset_index()
grouped_lists['Albumin/Creatinine_Res'] = grouped_lists['Albumin/Creatinine_Res'].apply(lambda x: list(set(x)))

data = grouped_lists[['Albumin/Creatinine_Res']]

def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence) - 1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

for index, row in data.iterrows() :
    raw_seq = data['Albumin/Creatinine_Res'].at[index]
    if len(data['Albumin/Creatinine_Res'].at[index]) > 8 :
        # define input sequence
# choose a number of time steps
        n_steps = 3
# split into samples
        X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))
        print(X)
# define model
        model = Sequential()
        model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
        model.add(Dense(1))
        model.compile(optimizer='adam', loss='mse')
# fit model
        model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
        x_input = np.asarray(raw_seq[-4:-1])
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        y_actual = np.asarray(raw_seq[-1:])
        rms = sqrt(mean_squared_error(y_actual, yhat))
        print(rms)

    else :
        continue


[[[ 36.]
  [ 37.]
  [  5.]]

 [[ 37.]
  [  5.]
  [ 68.]]

 [[  5.]
  [ 68.]
  [  8.]]

 [[ 68.]
  [  8.]
  [ 12.]]

 [[  8.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 16.]]

 [[ 13.]
  [ 16.]
  [ 53.]]

 [[ 16.]
  [ 53.]
  [ 55.]]

 [[ 53.]
  [ 55.]
  [186.]]

 [[ 55.]
  [186.]
  [ 27.]]]
0.24385452270507812
[[[ 1.]
  [ 2.]
  [ 4.]]

 [[ 2.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [ 9.]]

 [[ 8.]
  [ 9.]
  [11.]]

 [[ 9.]
  [11.]
  [12.]]

 [[11.]
  [12.]
  [13.]]]
0.035162925720214844
[[[1.]
  [2.]
  [3.]]

 [[2.]
  [3.]
  [4.]]

 [[3.]
  [4.]
  [5.]]

 [[4.]
  [5.]
  [6.]]

 [[5.]
  [6.]
  [7.]]

 [[6.]
  [7.]
  [8.]]]
1.2300338745117188
[[[ 1.]
  [ 8.]
  [72.]]

 [[ 8.]
  [72.]
  [13.]]

 [[72.]
  [13.]
  [48.]]

 [[13.]
  [48.]
  [17.]]

 [[48.]
  [17.]
  [19.]]

 [[17.]
  [19.]
  [51.]]

 [[19.]
  [51.]
  [23.]]]
10.187847137451172
[[[32.]
  [34.]
  [ 5.]]

 [[34.]
  [ 5.]
  [41.]]

 [[ 5.]
  [41.]
  [45.]]


1.4135055541992188
[[[ 3.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [42.]]

 [[ 8.]
  [42.]
  [12.]]

 [[42.]
  [12.]
  [16.]]

 [[12.]
  [16.]
  [48.]]]
0.03761100769042969
[[[  1.]
  [  3.]
  [  5.]]

 [[  3.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [136.]]

 [[  6.]
  [136.]
  [ 11.]]

 [[136.]
  [ 11.]
  [ 15.]]

 [[ 11.]
  [ 15.]
  [ 19.]]

 [[ 15.]
  [ 19.]
  [ 22.]]

 [[ 19.]
  [ 22.]
  [ 24.]]

 [[ 22.]
  [ 24.]
  [ 29.]]

 [[ 24.]
  [ 29.]
  [ 33.]]

 [[ 29.]
  [ 33.]
  [161.]]

 [[ 33.]
  [161.]
  [ 35.]]

 [[161.]
  [ 35.]
  [ 54.]]

 [[ 35.]
  [ 54.]
  [ 76.]]

 [[ 54.]
  [ 76.]
  [216.]]

 [[ 76.]
  [216.]
  [ 89.]]

 [[216.]
  [ 89.]
  [239.]]

 [[ 89.]
  [239.]
  [241.]]]
16.16619873046875
[[[ 33.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [266.]]

 [[  8.]
  [266.]
  [ 44.]]

 [[266.]
  [ 44.]
  [ 13.]]

 [[ 44.]
  [ 13.]
  [205.]]

 [[ 13.]
  [205.]
  [ 16.]]

 [[205.]
  [ 16.]
  [ 17.]]

 [[ 16.]
  [ 17.]
  [ 18.]]

 [[ 

0.17664337158203125
[[[256.]
  [ 34.]
  [  2.]]

 [[ 34.]
  [  2.]
  [ 36.]]

 [[  2.]
  [ 36.]
  [101.]]

 [[ 36.]
  [101.]
  [  7.]]

 [[101.]
  [  7.]
  [ 46.]]

 [[  7.]
  [ 46.]
  [ 15.]]

 [[ 46.]
  [ 15.]
  [ 14.]]

 [[ 15.]
  [ 14.]
  [ 19.]]]
0.016971588134765625
[[[128.]
  [  2.]
  [  3.]]

 [[  2.]
  [  3.]
  [ 34.]]

 [[  3.]
  [ 34.]
  [  8.]]

 [[ 34.]
  [  8.]
  [ 41.]]

 [[  8.]
  [ 41.]
  [107.]]

 [[ 41.]
  [107.]
  [ 76.]]

 [[107.]
  [ 76.]
  [ 77.]]

 [[ 76.]
  [ 77.]
  [ 79.]]

 [[ 77.]
  [ 79.]
  [ 17.]]

 [[ 79.]
  [ 17.]
  [ 83.]]]
0.10282707214355469
[[[ 35.]
  [  3.]
  [  5.]]

 [[  3.]
  [  5.]
  [131.]]

 [[  5.]
  [131.]
  [  7.]]

 [[131.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [ 73.]]

 [[  8.]
  [ 73.]
  [ 16.]]

 [[ 73.]
  [ 16.]
  [ 17.]]

 [[ 16.]
  [ 17.]
  [ 18.]]

 [[ 17.]
  [ 18.]
  [ 87.]]]
0.002685546875
[[[  2.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 11.

0.44831085205078125
[[[288.]
  [162.]
  [259.]]

 [[162.]
  [259.]
  [292.]]

 [[259.]
  [292.]
  [258.]]

 [[292.]
  [258.]
  [268.]]

 [[258.]
  [268.]
  [269.]]

 [[268.]
  [269.]
  [238.]]

 [[269.]
  [238.]
  [241.]]

 [[238.]
  [241.]
  [ 18.]]

 [[241.]
  [ 18.]
  [184.]]]
0.216796875
[[[ 98.]
  [194.]
  [  8.]]

 [[194.]
  [  8.]
  [168.]]

 [[  8.]
  [168.]
  [ 10.]]

 [[168.]
  [ 10.]
  [141.]]

 [[ 10.]
  [141.]
  [ 46.]]

 [[141.]
  [ 46.]
  [ 47.]]

 [[ 46.]
  [ 47.]
  [238.]]

 [[ 47.]
  [238.]
  [ 13.]]

 [[238.]
  [ 13.]
  [115.]]

 [[ 13.]
  [115.]
  [ 54.]]

 [[115.]
  [ 54.]
  [119.]]

 [[ 54.]
  [119.]
  [153.]]

 [[119.]
  [153.]
  [124.]]]
0.6565093994140625
[[[128.]
  [  3.]
  [  4.]]

 [[  3.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [ 13.]]

 [[  8.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [ 19.]]

 [[ 15.]
  [ 19.]
  [ 51.]]

 [[ 19.]
  [ 51.]
  [

3.0859546661376953
[[[129.]
  [  2.]
  [ 97.]]

 [[  2.]
  [ 97.]
  [  5.]]

 [[ 97.]
  [  5.]
  [  7.]]

 [[  5.]
  [  7.]
  [  9.]]

 [[  7.]
  [  9.]
  [ 11.]]

 [[  9.]
  [ 11.]
  [ 12.]]

 [[ 11.]
  [ 12.]
  [145.]]

 [[ 12.]
  [145.]
  [ 18.]]

 [[145.]
  [ 18.]
  [ 24.]]]
1.6785888671875
[[[ 1.]
  [33.]
  [ 2.]]

 [[33.]
  [ 2.]
  [ 4.]]

 [[ 2.]
  [ 4.]
  [ 7.]]

 [[ 4.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [ 9.]]

 [[ 8.]
  [ 9.]
  [12.]]]
2.0022029876708984
[[[ 2.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [72.]]

 [[ 6.]
  [72.]
  [41.]]

 [[72.]
  [41.]
  [14.]]

 [[41.]
  [14.]
  [21.]]

 [[14.]
  [21.]
  [22.]]

 [[21.]
  [22.]
  [23.]]]
2.4265995025634766
[[[ 96.]
  [  1.]
  [ 37.]]

 [[  1.]
  [ 37.]
  [198.]]

 [[ 37.]
  [198.]
  [  8.]]

 [[198.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [109.]]

 [[  9.]
  [109.]
  [ 15.]]

 [[109.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [245.]]]
0.9049625396728516
[[[ 2.]
  [ 5.]
  [ 8.]]

 [[ 5.]
  [ 8.]
  [ 9.]]

 [[ 8.]
  [ 9.]
  [12.]]


0.1158447265625
[[[185.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 12.]]

 [[  9.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 16.]]

 [[ 13.]
  [ 16.]
  [ 49.]]

 [[ 16.]
  [ 49.]
  [ 17.]]

 [[ 49.]
  [ 17.]
  [ 19.]]

 [[ 17.]
  [ 19.]
  [114.]]

 [[ 19.]
  [114.]
  [153.]]]
0.49869728088378906
[[[ 1.]
  [ 5.]
  [ 7.]]

 [[ 5.]
  [ 7.]
  [ 9.]]

 [[ 7.]
  [ 9.]
  [14.]]

 [[ 9.]
  [14.]
  [15.]]

 [[14.]
  [15.]
  [47.]]

 [[15.]
  [47.]
  [17.]]]
0.5215606689453125
[[[ 32.]
  [ 39.]
  [ 41.]]

 [[ 39.]
  [ 41.]
  [106.]]

 [[ 41.]
  [106.]
  [205.]]

 [[106.]
  [205.]
  [111.]]

 [[205.]
  [111.]
  [ 21.]]

 [[111.]
  [ 21.]
  [ 22.]]

 [[ 21.]
  [ 22.]
  [ 25.]]

 [[ 22.]
  [ 25.]
  [ 27.]]]
1.9847946166992188
[[[ 1.]
  [65.]
  [ 3.]]

 [[65.]
  [ 3.]
  [ 5.]]

 [[ 3.]
  [ 5.]
  [38.]]

 [[ 5.]
  [38.]
  [ 6.]]

 [[38.]
  [ 6.]
  [14.]]

 [[ 6.]
  [14.]
  [18.]]

 [[14.]
  [18.]
  [19.]]

 [[18.]


6.103515625e-05
[[[ 89.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 11.]]

 [[  9.]
  [ 11.]
  [ 79.]]

 [[ 11.]
  [ 79.]
  [ 15.]]

 [[ 79.]
  [ 15.]
  [242.]]]
0.10628128051757812
[[[ 1.]
  [ 9.]
  [11.]]

 [[ 9.]
  [11.]
  [12.]]

 [[11.]
  [12.]
  [13.]]

 [[12.]
  [13.]
  [92.]]

 [[13.]
  [92.]
  [16.]]

 [[92.]
  [16.]
  [18.]]]
0.9721698760986328
[[[ 33.]
  [ 65.]
  [ 35.]]

 [[ 65.]
  [ 35.]
  [102.]]

 [[ 35.]
  [102.]
  [  7.]]

 [[102.]
  [  7.]
  [ 43.]]

 [[  7.]
  [ 43.]
  [ 46.]]

 [[ 43.]
  [ 46.]
  [ 16.]]

 [[ 46.]
  [ 16.]
  [145.]]

 [[ 16.]
  [145.]
  [ 52.]]

 [[145.]
  [ 52.]
  [ 85.]]]
0.039485931396484375
[[[129.]
  [259.]
  [ 69.]]

 [[259.]
  [ 69.]
  [165.]]

 [[ 69.]
  [165.]
  [296.]]

 [[165.]
  [296.]
  [106.]]

 [[296.]
  [106.]
  [ 79.]]

 [[106.]
  [ 79.]
  [182.]]

 [[ 79.]
  [182.]
  [118.]]

 [[182.]
  [118.]
  [187.]]]
4.458618164062

0.07230567932128906
[[[ 33.]
  [  2.]
  [ 34.]]

 [[  2.]
  [ 34.]
  [  4.]]

 [[ 34.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [ 39.]]

 [[  5.]
  [ 39.]
  [141.]]

 [[ 39.]
  [141.]
  [ 45.]]

 [[141.]
  [ 45.]
  [ 16.]]

 [[ 45.]
  [ 16.]
  [ 25.]]]
0.026737213134765625
[[[224.]
  [  1.]
  [ 13.]]

 [[  1.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 19.]]

 [[ 16.]
  [ 19.]
  [ 21.]]

 [[ 19.]
  [ 21.]
  [ 26.]]]
56.54106140136719
[[[  1.]
  [259.]
  [132.]]

 [[259.]
  [132.]
  [ 39.]]

 [[132.]
  [ 39.]
  [233.]]

 [[ 39.]
  [233.]
  [144.]]

 [[233.]
  [144.]
  [ 49.]]

 [[144.]
  [ 49.]
  [ 16.]]

 [[ 49.]
  [ 16.]
  [148.]]]
0.04558563232421875
[[[ 33.]
  [163.]
  [ 36.]]

 [[163.]
  [ 36.]
  [ 37.]]

 [[ 36.]
  [ 37.]
  [102.]]

 [[ 37.]
  [102.]
  [134.]]

 [[102.]
  [134.]
  [ 43.]]

 [[134.]
  [ 43.]
  [ 44.]]

 [[ 43.]
  [ 44.]
  [ 46.]]

 [[ 44.]
  [ 46.]
  [ 58.]]

 [[ 46.]
  [ 58.]
  [156.]]]
1.8451385498046875
[[[

0.11425018310546875
[[[129.]
  [  1.]
  [131.]]

 [[  1.]
  [131.]
  [  6.]]

 [[131.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  9.]]

 [[  7.]
  [  9.]
  [171.]]

 [[  9.]
  [171.]
  [ 14.]]]
0.6230926513671875
[[[  1.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  9.]]

 [[  7.]
  [  9.]
  [266.]]

 [[  9.]
  [266.]
  [234.]]]
5.128135681152344
[[[ 64.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  9.]]

 [[  7.]
  [  9.]
  [ 13.]]

 [[  9.]
  [ 13.]
  [ 45.]]

 [[ 13.]
  [ 45.]
  [173.]]

 [[ 45.]
  [173.]
  [ 16.]]]
0.0108642578125
[[[128.]
  [165.]
  [ 72.]]

 [[165.]
  [ 72.]
  [ 42.]]

 [[ 72.]
  [ 42.]
  [ 11.]]

 [[ 42.]
  [ 11.]
  [ 79.]]

 [[ 11.]
  [ 79.]
  [144.]]

 [[ 79.]
  [144.]
  [ 25.]]]
0.0048065185546875
[[[  3.]
  [135.]
  [  8.]]

 [[135.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 12.]]

 [[  9.]
  [ 12.]
  [141.]]

 [[ 12.]
  [141.]
  [ 16.]]

 [[141.]


0.043788909912109375
[[[  3.]
  [ 35.]
  [ 12.]]

 [[ 35.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [206.]]

 [[ 14.]
  [206.]
  [ 18.]]

 [[206.]
  [ 18.]
  [ 19.]]]
0.024051666259765625
[[[129.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [ 13.]]

 [[  8.]
  [ 13.]
  [ 84.]]

 [[ 13.]
  [ 84.]
  [ 21.]]

 [[ 84.]
  [ 21.]
  [121.]]]
0.027801513671875
[[[ 33.]
  [  1.]
  [195.]]

 [[  1.]
  [195.]
  [  4.]]

 [[195.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  2.]]

 [[  5.]
  [  2.]
  [  7.]]

 [[  2.]
  [  7.]
  [  9.]]

 [[  7.]
  [  9.]
  [ 19.]]]
1.822906494140625
[[[  1.]
  [  3.]
  [  4.]]

 [[  3.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [ 11.]]

 [[  7.]
  [ 11.]
  [ 13.]]

 [[ 11.]
  [ 13.]
  [111.]]

 [[ 13.]
  [111.]
  [115.]]

 [[111.]
  [115.]
  [148.]]

 [[115.]
  [148.]
  [ 23.]]]
0.4185028076171875
[[[192.]
  [  1.]
  [  2.]]

 [[  1.]
  [  2.]
  [ 96.]]

 [[ 

0.48444366455078125
[[[131.]
  [260.]
  [ 18.]]

 [[260.]
  [ 18.]
  [152.]]

 [[ 18.]
  [152.]
  [ 24.]]

 [[152.]
  [ 24.]
  [ 26.]]

 [[ 24.]
  [ 26.]
  [ 46.]]

 [[ 26.]
  [ 46.]
  [175.]]

 [[ 46.]
  [175.]
  [ 61.]]

 [[175.]
  [ 61.]
  [ 63.]]

 [[ 61.]
  [ 63.]
  [ 64.]]

 [[ 63.]
  [ 64.]
  [200.]]

 [[ 64.]
  [200.]
  [215.]]

 [[200.]
  [215.]
  [221.]]

 [[215.]
  [221.]
  [102.]]

 [[221.]
  [102.]
  [237.]]

 [[102.]
  [237.]
  [239.]]

 [[237.]
  [239.]
  [117.]]]
11.89453125
[[[ 1.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [12.]]

 [[ 8.]
  [12.]
  [13.]]

 [[12.]
  [13.]
  [55.]]

 [[13.]
  [55.]
  [57.]]]
0.8562812805175781
[[[ 99.]
  [ 38.]
  [167.]]

 [[ 38.]
  [167.]
  [171.]]

 [[167.]
  [171.]
  [ 81.]]

 [[171.]
  [ 81.]
  [275.]]

 [[ 81.]
  [275.]
  [ 83.]]

 [[275.]
  [ 83.]
  [ 21.]]]
0.0902252197265625
[[[  2.]
  [  3.]
  [227.]]

 [[  3.]
  [227.]
  [  5.]]

 [[227.]
  [  5.]
  [  7.]]

 [[  5.]
  [  7.]
  [199.]]

 [[  7.]
  [199.]
  

0.2206878662109375
[[[ 3.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [38.]]

 [[ 5.]
  [38.]
  [45.]]

 [[38.]
  [45.]
  [48.]]

 [[45.]
  [48.]
  [27.]]

 [[48.]
  [27.]
  [29.]]]
0.01010894775390625
[[[ 64.]
  [  1.]
  [  2.]]

 [[  1.]
  [  2.]
  [  6.]]

 [[  2.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [ 73.]]

 [[  7.]
  [ 73.]
  [106.]]

 [[ 73.]
  [106.]
  [ 11.]]

 [[106.]
  [ 11.]
  [ 12.]]

 [[ 11.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 79.]]

 [[ 13.]
  [ 79.]
  [ 16.]]

 [[ 79.]
  [ 16.]
  [ 81.]]

 [[ 16.]
  [ 81.]
  [ 51.]]

 [[ 81.]
  [ 51.]
  [ 53.]]

 [[ 51.]
  [ 53.]
  [ 22.]]

 [[ 53.]
  [ 22.]
  [ 62.]]]
0.5603408813476562
[[[33.]
  [ 2.]
  [ 1.]]

 [[ 2.]
  [ 1.]
  [ 4.]]

 [[ 1.]
  [ 4.]
  [ 6.]]

 [[ 4.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [45.]]

 [[ 7.]
  [45.]
  [14.]]]
2.32452392578125
[[[  1.]
  [ 37.]
  [  8.]]

 [[ 37.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [105.]]

 [[  9.]
  [105.]
  [ 13.]]

 [[105.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 

0.0556640625
[[[  3.]
  [ 74.]
  [ 14.]]

 [[ 74.]
  [ 14.]
  [ 47.]]

 [[ 14.]
  [ 47.]
  [143.]]

 [[ 47.]
  [143.]
  [ 18.]]

 [[143.]
  [ 18.]
  [ 21.]]

 [[ 18.]
  [ 21.]
  [ 23.]]

 [[ 21.]
  [ 23.]
  [ 89.]]]
1.24560546875
[[[  1.]
  [193.]
  [259.]]

 [[193.]
  [259.]
  [  4.]]

 [[259.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [101.]]

 [[  6.]
  [101.]
  [  8.]]

 [[101.]
  [  8.]
  [104.]]

 [[  8.]
  [104.]
  [144.]]]
0.22815704345703125
[[[  1.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [105.]]

 [[  8.]
  [105.]
  [  9.]]

 [[105.]
  [  9.]
  [ 11.]]

 [[  9.]
  [ 11.]
  [ 46.]]]
0.81549072265625
[[[ 32.]
  [  1.]
  [ 64.]]

 [[  1.]
  [ 64.]
  [  3.]]

 [[ 64.]
  [  3.]
  [  4.]]

 [[  3.]
  [  4.]
  [132.]]

 [[  4.]
  [132.]
  [  8.]]

 [[132.]
  [  8.]
  [ 12.]]

 [[  8.]
  [ 12.]
  [145.]]

 [[ 12.]
  [145.]
  [116.]]

 [[145.]
  [116.]
  [ 86.]]]
3.367156

0.534576416015625
[[[  4.]
  [  8.]
  [ 72.]]

 [[  8.]
  [ 72.]
  [ 42.]]

 [[ 72.]
  [ 42.]
  [ 13.]]

 [[ 42.]
  [ 13.]
  [ 18.]]

 [[ 13.]
  [ 18.]
  [122.]]

 [[ 18.]
  [122.]
  [ 28.]]

 [[122.]
  [ 28.]
  [ 62.]]]
0.2657642364501953
[[[  5.]
  [ 41.]
  [265.]]

 [[ 41.]
  [265.]
  [ 43.]]

 [[265.]
  [ 43.]
  [ 12.]]

 [[ 43.]
  [ 12.]
  [139.]]

 [[ 12.]
  [139.]
  [ 57.]]

 [[139.]
  [ 57.]
  [ 26.]]]
0.041347503662109375
[[[32.]
  [ 2.]
  [ 3.]]

 [[ 2.]
  [ 3.]
  [ 4.]]

 [[ 3.]
  [ 4.]
  [35.]]

 [[ 4.]
  [35.]
  [ 7.]]

 [[35.]
  [ 7.]
  [11.]]

 [[ 7.]
  [11.]
  [53.]]]
1.4477386474609375
[[[161.]
  [  6.]
  [  8.]]

 [[  6.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [168.]]

 [[  9.]
  [168.]
  [264.]]

 [[168.]
  [264.]
  [108.]]

 [[264.]
  [108.]
  [ 14.]]

 [[108.]
  [ 14.]
  [208.]]

 [[ 14.]
  [208.]
  [ 49.]]]
2.070415496826172
[[[ 33.]
  [  1.]
  [ 99.]]

 [[  1.]
  [ 99.]
  [ 37.]]

 [[ 99.]
  [ 37.]
  [ 38.]]

 [[ 37.]
  [ 38.]
  [101.]]

 [[ 38.]
  [101.]
  [  8

31.908287048339844
[[[33.]
  [34.]
  [67.]]

 [[34.]
  [67.]
  [ 6.]]

 [[67.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [41.]]

 [[ 7.]
  [41.]
  [14.]]

 [[41.]
  [14.]
  [79.]]

 [[14.]
  [79.]
  [83.]]]
0.112945556640625
[[[ 64.]
  [ 34.]
  [  7.]]

 [[ 34.]
  [  7.]
  [103.]]

 [[  7.]
  [103.]
  [ 41.]]

 [[103.]
  [ 41.]
  [106.]]

 [[ 41.]
  [106.]
  [108.]]

 [[106.]
  [108.]
  [ 45.]]

 [[108.]
  [ 45.]
  [ 76.]]

 [[ 45.]
  [ 76.]
  [146.]]

 [[ 76.]
  [146.]
  [ 55.]]

 [[146.]
  [ 55.]
  [ 57.]]

 [[ 55.]
  [ 57.]
  [ 93.]]]
0.149261474609375
[[[  1.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [ 11.]]

 [[  8.]
  [ 11.]
  [ 13.]]

 [[ 11.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [ 17.]]

 [[ 15.]
  [ 17.]
  [ 19.]]

 [[ 17.]
  [ 19.]
  [ 21.]]

 [[ 19.]
  [ 21.]
  [ 23.]]

 [[ 21.]
  [ 23.]
  [284.]]

 [[ 23.]
  [284.]
  [ 45.]]

 [[284.]
  [ 45.]
  [ 47.]]

 [[ 45.]
  [ 47.]
  [214.]]

 [[ 47.]
  [214.]
  [ 93.]]

 [[214.]
  [ 93.]
  [ 96.]]

 [[ 93.]


2.0312938690185547
[[[  5.]
  [ 71.]
  [201.]]

 [[ 71.]
  [201.]
  [ 74.]]

 [[201.]
  [ 74.]
  [187.]]

 [[ 74.]
  [187.]
  [178.]]

 [[187.]
  [178.]
  [119.]]

 [[178.]
  [119.]
  [ 25.]]

 [[119.]
  [ 25.]
  [ 27.]]

 [[ 25.]
  [ 27.]
  [ 28.]]

 [[ 27.]
  [ 28.]
  [ 61.]]]
0.01923370361328125
[[[ 99.]
  [ 71.]
  [  9.]]

 [[ 71.]
  [  9.]
  [137.]]

 [[  9.]
  [137.]
  [ 42.]]

 [[137.]
  [ 42.]
  [ 15.]]

 [[ 42.]
  [ 15.]
  [ 21.]]

 [[ 15.]
  [ 21.]
  [ 86.]]]
0.0476837158203125
[[[ 96.]
  [ 68.]
  [ 41.]]

 [[ 68.]
  [ 41.]
  [ 15.]]

 [[ 41.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 48.]]

 [[ 16.]
  [ 48.]
  [115.]]

 [[ 48.]
  [115.]
  [ 21.]]

 [[115.]
  [ 21.]
  [152.]]]
0.00725555419921875
[[[  1.]
  [  3.]
  [  5.]]

 [[  3.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [ 38.]]

 [[  6.]
  [ 38.]
  [  8.]]

 [[ 38.]
  [  8.]
  [138.]]

 [[  8.]
  [138.]
  [ 11.]]

 [[138.]
  [ 11.]
  [ 14.]]

 [[ 11.]
  [ 14.]
  [ 78.]]

 [[ 14.]
  [ 78.]
  [ 48.]]

 [[ 78.]
  [ 48.]
  [ 2

2.120939254760742
[[[ 1.]
  [69.]
  [ 6.]]

 [[69.]
  [ 6.]
  [ 9.]]

 [[ 6.]
  [ 9.]
  [11.]]

 [[ 9.]
  [11.]
  [12.]]

 [[11.]
  [12.]
  [15.]]

 [[12.]
  [15.]
  [16.]]]
0.4381732940673828
[[[ 4.]
  [ 6.]
  [71.]]

 [[ 6.]
  [71.]
  [ 9.]]

 [[71.]
  [ 9.]
  [73.]]

 [[ 9.]
  [73.]
  [11.]]

 [[73.]
  [11.]
  [12.]]

 [[11.]
  [12.]
  [19.]]

 [[12.]
  [19.]
  [21.]]

 [[19.]
  [21.]
  [26.]]

 [[21.]
  [26.]
  [28.]]]
11.716743469238281
[[[ 1.]
  [34.]
  [ 3.]]

 [[34.]
  [ 3.]
  [36.]]

 [[ 3.]
  [36.]
  [ 4.]]

 [[36.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [ 7.]]

 [[ 5.]
  [ 7.]
  [ 6.]]

 [[ 7.]
  [ 6.]
  [ 8.]]

 [[ 6.]
  [ 8.]
  [ 9.]]

 [[ 8.]
  [ 9.]
  [43.]]

 [[ 9.]
  [43.]
  [11.]]

 [[43.]
  [11.]
  [13.]]

 [[11.]
  [13.]
  [15.]]

 [[13.]
  [15.]
  [16.]]

 [[15.]
  [16.]
  [23.]]]
1.6895561218261719
[[[  3.]
  [195.]
  [ 37.]]

 [[195.]
  [ 37.]
  [ 38.]]

 [[ 37.]
  [ 38.]
  [ 72.]]

 [[ 38.]
  [ 72.]
  [ 47.]]

 [[ 72.]
  [ 47.]
  [208.]]

 [[ 47.]
  [208.]
  [ 81.]

0.435882568359375
[[[  1.]
  [  2.]
  [  4.]]

 [[  2.]
  [  4.]
  [ 38.]]

 [[  4.]
  [ 38.]
  [  7.]]

 [[ 38.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [139.]]

 [[  9.]
  [139.]
  [ 12.]]

 [[139.]
  [ 12.]
  [ 75.]]

 [[ 12.]
  [ 75.]
  [ 14.]]

 [[ 75.]
  [ 14.]
  [ 21.]]

 [[ 14.]
  [ 21.]
  [ 29.]]]
1.2596206665039062
[[[ 1.]
  [ 2.]
  [35.]]

 [[ 2.]
  [35.]
  [33.]]

 [[35.]
  [33.]
  [37.]]

 [[33.]
  [37.]
  [ 7.]]

 [[37.]
  [ 7.]
  [41.]]

 [[ 7.]
  [41.]
  [22.]]

 [[41.]
  [22.]
  [57.]]

 [[22.]
  [57.]
  [26.]]

 [[57.]
  [26.]
  [29.]]]
0.015003204345703125
[[[ 2.]
  [ 9.]
  [11.]]

 [[ 9.]
  [11.]
  [12.]]

 [[11.]
  [12.]
  [13.]]

 [[12.]
  [13.]
  [15.]]

 [[13.]
  [15.]
  [17.]]

 [[15.]
  [17.]
  [25.]]

 [[17.]
  [25.]
  [26.]]]
2.1695327758789062
[[[32.]
  [33.]
  [36.]]

 [[33.]
  [36.]
  [68.]]

 [[36.]
  [68.]
  [39.]]

 [[68.]
  [39.]
  [72.]]

 [[39.]
  [72.]
  [42.]]

 [[72.]
  [42.]
  [22.]]

 [[42.]
  [22.]
  [23.]]

 [[22.

0.29571533203125
[[[ 34.]
  [132.]
  [  8.]]

 [[132.]
  [  8.]
  [ 13.]]

 [[  8.]
  [ 13.]
  [ 15.]]

 [[ 13.]
  [ 15.]
  [244.]]

 [[ 15.]
  [244.]
  [ 85.]]

 [[244.]
  [ 85.]
  [279.]]]
1.377593994140625
[[[  2.]
  [ 37.]
  [103.]]

 [[ 37.]
  [103.]
  [ 12.]]

 [[103.]
  [ 12.]
  [ 15.]]

 [[ 12.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 23.]]

 [[ 16.]
  [ 23.]
  [ 25.]]]
0.45020484924316406
[[[ 1.]
  [68.]
  [ 5.]]

 [[68.]
  [ 5.]
  [ 7.]]

 [[ 5.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [ 9.]]

 [[ 8.]
  [ 9.]
  [71.]]

 [[ 9.]
  [71.]
  [11.]]

 [[71.]
  [11.]
  [77.]]

 [[11.]
  [77.]
  [87.]]

 [[77.]
  [87.]
  [89.]]]
0.3124732971191406
[[[128.]
  [224.]
  [ 41.]]

 [[224.]
  [ 41.]
  [173.]]

 [[ 41.]
  [173.]
  [ 14.]]

 [[173.]
  [ 14.]
  [ 16.]]

 [[ 14.]
  [ 16.]
  [ 17.]]

 [[ 16.]
  [ 17.]
  [ 49.]]]
4.837100982666016
[[[192.]
  [196.]
  [231.]]

 [[196.]
  [231.]
  [136.]]

 [[231.]
  [136.]
  [137.]]

 [[136.]
  [137.]
  [ 42.]]

 [[137.]
  [ 42.]
  [146.]]

 [[ 42.

2.5153579711914062
[[[  1.]
  [  2.]
  [  5.]]

 [[  2.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 41.]]

 [[  9.]
  [ 41.]
  [ 37.]]

 [[ 41.]
  [ 37.]
  [266.]]

 [[ 37.]
  [266.]
  [237.]]

 [[266.]
  [237.]
  [ 14.]]

 [[237.]
  [ 14.]
  [ 39.]]

 [[ 14.]
  [ 39.]
  [ 25.]]]
3.3985557556152344
[[[  1.]
  [  2.]
  [  4.]]

 [[  2.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  8.]]

 [[  6.]
  [  8.]
  [ 13.]]

 [[  8.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 17.]]

 [[ 14.]
  [ 17.]
  [ 19.]]

 [[ 17.]
  [ 19.]
  [183.]]]
0.33945465087890625
[[[ 32.]
  [  1.]
  [  2.]]

 [[  1.]
  [  2.]
  [  5.]]

 [[  2.]
  [  5.]
  [  7.]]

 [[  5.]
  [  7.]
  [ 13.]]

 [[  7.]
  [ 13.]
  [239.]]

 [[ 13.]
  [239.]
  [ 19.]]

 [[239.]
  [ 19.]
  [212.]]

 [[ 19.]
  [212.]
  [243.]]]
10.262443542480469
[[[36.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [38.]]

 [[ 

0.02571868896484375
[[[ 4.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [71.]]

 [[ 8.]
  [71.]
  [68.]]

 [[71.]
  [68.]
  [11.]]

 [[68.]
  [11.]
  [46.]]

 [[11.]
  [46.]
  [94.]]]
0.29132080078125
[[[  5.]
  [104.]
  [ 41.]]

 [[104.]
  [ 41.]
  [ 11.]]

 [[ 41.]
  [ 11.]
  [ 12.]]

 [[ 11.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 15.]]

 [[ 13.]
  [ 15.]
  [ 49.]]

 [[ 15.]
  [ 49.]
  [ 24.]]

 [[ 49.]
  [ 24.]
  [ 28.]]]
0.0468292236328125
[[[  2.]
  [ 37.]
  [  6.]]

 [[ 37.]
  [  6.]
  [ 41.]]

 [[  6.]
  [ 41.]
  [ 44.]]

 [[ 41.]
  [ 44.]
  [141.]]

 [[ 44.]
  [141.]
  [108.]]

 [[141.]
  [108.]
  [109.]]

 [[108.]
  [109.]
  [153.]]]
1.912353515625
[[[  2.]
  [ 99.]
  [  4.]]

 [[ 99.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [ 35.]]

 [[  7.]
  [ 35.]
  [ 47.]]

 [[ 35.]
  [ 47.]
  [181.]]]
0.12011337280273438
[[[ 32.]
  [217.]
  [ 11.]]

 [[217.]
  [ 11.]
  [ 12.]]

 [[ 1

0.05783843994140625
[[[129.]
  [ 67.]
  [  5.]]

 [[ 67.]
  [  5.]
  [105.]]

 [[  5.]
  [105.]
  [ 73.]]

 [[105.]
  [ 73.]
  [ 76.]]

 [[ 73.]
  [ 76.]
  [141.]]

 [[ 76.]
  [141.]
  [ 46.]]

 [[141.]
  [ 46.]
  [119.]]]
0.011810302734375
[[[33.]
  [34.]
  [36.]]

 [[34.]
  [36.]
  [46.]]

 [[36.]
  [46.]
  [17.]]

 [[46.]
  [17.]
  [19.]]

 [[17.]
  [19.]
  [51.]]

 [[19.]
  [51.]
  [26.]]]
1.4278793334960938
[[[ 32.]
  [  1.]
  [  4.]]

 [[  1.]
  [  4.]
  [ 37.]]

 [[  4.]
  [ 37.]
  [ 38.]]

 [[ 37.]
  [ 38.]
  [  7.]]

 [[ 38.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [ 11.]]

 [[  8.]
  [ 11.]
  [ 12.]]

 [[ 11.]
  [ 12.]
  [ 51.]]

 [[ 12.]
  [ 51.]
  [ 52.]]

 [[ 51.]
  [ 52.]
  [153.]]

 [[ 52.]
  [153.]
  [ 27.]]]
0.6945457458496094
[[[  1.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 71.]]

 [[  9.]
  [ 71.]
  [ 13.]]

 [[ 71.]
  [ 13.]
  [ 47.]]

 [[ 13.]
  [ 47.]
  [115.]]]
0.110992431640

7.183036804199219
[[[128.]
  [  8.]
  [ 12.]]

 [[  8.]
  [ 12.]
  [142.]]

 [[ 12.]
  [142.]
  [ 17.]]

 [[142.]
  [ 17.]
  [ 18.]]

 [[ 17.]
  [ 18.]
  [ 19.]]

 [[ 18.]
  [ 19.]
  [ 21.]]

 [[ 19.]
  [ 21.]
  [ 24.]]

 [[ 21.]
  [ 24.]
  [ 25.]]

 [[ 24.]
  [ 25.]
  [ 27.]]

 [[ 25.]
  [ 27.]
  [ 29.]]

 [[ 27.]
  [ 29.]
  [ 46.]]

 [[ 29.]
  [ 46.]
  [ 47.]]

 [[ 46.]
  [ 47.]
  [ 63.]]

 [[ 47.]
  [ 63.]
  [ 67.]]

 [[ 63.]
  [ 67.]
  [ 75.]]

 [[ 67.]
  [ 75.]
  [ 87.]]

 [[ 75.]
  [ 87.]
  [ 91.]]

 [[ 87.]
  [ 91.]
  [102.]]]
1.6919403076171875
[[[  1.]
  [129.]
  [  5.]]

 [[129.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 11.]]

 [[  9.]
  [ 11.]
  [ 12.]]

 [[ 11.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [ 17.]]

 [[ 15.]
  [ 17.]
  [ 18.]]

 [[ 17.]
  [ 18.]
  [ 19.]]

 [[ 18.]
  [ 19.]
  [ 22.]]

 [[ 19.]
  [ 22.]
  [ 26.]]

 [[ 22

0.07213592529296875
[[[  1.]
  [  3.]
  [166.]]

 [[  3.]
  [166.]
  [  8.]]

 [[166.]
  [  8.]
  [ 13.]]

 [[  8.]
  [ 13.]
  [ 15.]]

 [[ 13.]
  [ 15.]
  [ 17.]]

 [[ 15.]
  [ 17.]
  [ 82.]]

 [[ 17.]
  [ 82.]
  [ 84.]]

 [[ 82.]
  [ 84.]
  [ 86.]]]
2.1719284057617188
[[[  3.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [ 12.]]

 [[  7.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [114.]]

 [[ 13.]
  [114.]
  [ 19.]]

 [[114.]
  [ 19.]
  [ 18.]]

 [[ 19.]
  [ 18.]
  [187.]]]
1.4157943725585938
[[[ 32.]
  [228.]
  [ 69.]]

 [[228.]
  [ 69.]
  [ 41.]]

 [[ 69.]
  [ 41.]
  [ 44.]]

 [[ 41.]
  [ 44.]
  [207.]]

 [[ 44.]
  [207.]
  [113.]]

 [[207.]
  [113.]
  [149.]]

 [[113.]
  [149.]
  [182.]]

 [[149.]
  [182.]
  [154.]]]
0.00466156005859375
[[[ 97.]
  [  3.]
  [ 36.]]

 [[  3.]
  [ 36.]
  [  7.]]

 [[ 36.]
  [  7.]
  [ 39.]]

 [[  7.]
  [ 39.]
  [ 41.]]

 [[ 39.]
  [ 41.]
  [  9.]]

 [[ 41.]
  [  9.]
  [ 43.]]

 [[  9.]
  [ 43.]
  [231.]]

 [[ 43.]
  [231.]
  [ 16.]]

 [[231.]
  [ 16.]
  [ 8

0.1477203369140625
[[[  1.]
  [  2.]
  [  9.]]

 [[  2.]
  [  9.]
  [ 12.]]

 [[  9.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 17.]]

 [[ 16.]
  [ 17.]
  [148.]]

 [[ 17.]
  [148.]
  [ 22.]]

 [[148.]
  [ 22.]
  [ 23.]]

 [[ 22.]
  [ 23.]
  [ 27.]]

 [[ 23.]
  [ 27.]
  [ 33.]]

 [[ 27.]
  [ 33.]
  [ 37.]]

 [[ 33.]
  [ 37.]
  [178.]]

 [[ 37.]
  [178.]
  [ 64.]]

 [[178.]
  [ 64.]
  [ 76.]]]
3.1188812255859375
[[[  3.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [ 17.]]

 [[  8.]
  [ 17.]
  [ 21.]]

 [[ 17.]
  [ 21.]
  [ 26.]]

 [[ 21.]
  [ 26.]
  [ 31.]]

 [[ 26.]
  [ 31.]
  [ 32.]]

 [[ 31.]
  [ 32.]
  [ 42.]]

 [[ 32.]
  [ 42.]
  [178.]]

 [[ 42.]
  [178.]
  [ 52.]]

 [[178.]
  [ 52.]
  [ 53.]]

 [[ 52.]
  [ 53.]
  [ 55.]]

 [[ 53.]
  [ 55.]
  [ 68.]]

 [[ 55.]
  [ 68.]
  [ 89.]]]
0.1797943115234375
[[[  1.]
  [ 66

1.4819488525390625
[[[  1.]
  [  5.]
  [  7.]]

 [[  5.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 12.]]

 [[  9.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 17.]]

 [[ 16.]
  [ 17.]
  [ 19.]]

 [[ 17.]
  [ 19.]
  [ 54.]]

 [[ 19.]
  [ 54.]
  [ 64.]]

 [[ 54.]
  [ 64.]
  [ 67.]]

 [[ 64.]
  [ 67.]
  [ 74.]]

 [[ 67.]
  [ 74.]
  [ 91.]]

 [[ 74.]
  [ 91.]
  [109.]]]
3.0046310424804688
[[[162.]
  [194.]
  [196.]]

 [[194.]
  [196.]
  [133.]]

 [[196.]
  [133.]
  [137.]]

 [[133.]
  [137.]
  [201.]]

 [[137.]
  [201.]
  [ 11.]]

 [[201.]
  [ 11.]
  [ 76.]]

 [[ 11.]
  [ 76.]
  [238.]]

 [[ 76.]
  [238.]
  [ 82.]]

 [[238.]
  [ 82.]
  [ 84.]]

 [[ 82.]
  [ 84.]
  [119.]]]
1.498565673828125
[[[ 64.]
  [  1.]
  [ 34.]]

 [[  1.]
  [ 34.]
  [  7.]]

 [[ 34.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 72.]]

 [[  9.]
  [ 72.]
  [ 15.]]

 [[ 72.]
  [ 15.

3.0387115478515625
[[[185.]
  [  9.]
  [ 11.]]

 [[  9.]
  [ 11.]
  [204.]]

 [[ 11.]
  [204.]
  [ 13.]]

 [[204.]
  [ 13.]
  [175.]]

 [[ 13.]
  [175.]
  [114.]]

 [[175.]
  [114.]
  [ 25.]]]
0.06585693359375
[[[  1.]
  [ 98.]
  [133.]]

 [[ 98.]
  [133.]
  [  7.]]

 [[133.]
  [  7.]
  [103.]]

 [[  7.]
  [103.]
  [  9.]]

 [[103.]
  [  9.]
  [105.]]

 [[  9.]
  [105.]
  [137.]]

 [[105.]
  [137.]
  [204.]]

 [[137.]
  [204.]
  [ 14.]]

 [[204.]
  [ 14.]
  [142.]]

 [[ 14.]
  [142.]
  [ 78.]]

 [[142.]
  [ 78.]
  [147.]]

 [[ 78.]
  [147.]
  [117.]]

 [[147.]
  [117.]
  [119.]]]
7.3500518798828125
[[[257.]
  [  2.]
  [131.]]

 [[  2.]
  [131.]
  [139.]]

 [[131.]
  [139.]
  [ 16.]]

 [[139.]
  [ 16.]
  [ 19.]]

 [[ 16.]
  [ 19.]
  [ 21.]]

 [[ 19.]
  [ 21.]
  [ 23.]]

 [[ 21.]
  [ 23.]
  [ 24.]]

 [[ 23.]
  [ 24.]
  [ 27.]]

 [[ 24.]
  [ 27.]
  [156.]]

 [[ 27.]
  [156.]
  [ 35.]]

 [[156.]
  [ 35.]
  [ 37.]]

 [[ 35.]
  [ 37.]
  [166.]]

 [[ 37.]
  [166.]
  [ 42.]]

 [[166.]
  [ 42.]

13.175399780273438
[[[ 1.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [43.]]

 [[ 8.]
  [43.]
  [11.]]]
0.3169565200805664
[[[  1.]
  [  3.]
  [  4.]]

 [[  3.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [227.]]

 [[  5.]
  [227.]
  [ 12.]]

 [[227.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [142.]]

 [[ 14.]
  [142.]
  [ 16.]]

 [[142.]
  [ 16.]
  [271.]]

 [[ 16.]
  [271.]
  [ 21.]]

 [[271.]
  [ 21.]
  [151.]]

 [[ 21.]
  [151.]
  [ 24.]]

 [[151.]
  [ 24.]
  [187.]]]
0.5245590209960938
[[[33.]
  [ 2.]
  [ 3.]]

 [[ 2.]
  [ 3.]
  [ 5.]]

 [[ 3.]
  [ 5.]
  [ 7.]]

 [[ 5.]
  [ 7.]
  [72.]]

 [[ 7.]
  [72.]
  [74.]]

 [[72.]
  [74.]
  [75.]]

 [[74.]
  [75.]
  [55.]]

 [[75.]
  [55.]
  [89.]]]
0.061717987060546875
[[[  3.]
  [131.]
  [  9.]]

 [[131.]
  [  9.]
  [ 13.]]

 [[  9.]
  [ 13.]
  [ 15.]]

 [[ 13.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 19.]]

 [[ 16.]
  [ 19.]
  [ 20.]]

 [[ 19.

2.7144927978515625
[[[  1.]
  [259.]
  [ 37.]]

 [[259.]
  [ 37.]
  [ 38.]]

 [[ 37.]
  [ 38.]
  [  9.]]

 [[ 38.]
  [  9.]
  [105.]]

 [[  9.]
  [105.]
  [ 11.]]

 [[105.]
  [ 11.]
  [ 45.]]

 [[ 11.]
  [ 45.]
  [ 15.]]

 [[ 45.]
  [ 15.]
  [ 21.]]

 [[ 15.]
  [ 21.]
  [ 22.]]

 [[ 21.]
  [ 22.]
  [ 23.]]

 [[ 22.]
  [ 23.]
  [ 24.]]

 [[ 23.]
  [ 24.]
  [149.]]

 [[ 24.]
  [149.]
  [ 27.]]]
0.5634746551513672
[[[ 2.]
  [ 3.]
  [ 4.]]

 [[ 3.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 9.]]

 [[ 6.]
  [ 9.]
  [43.]]

 [[ 9.]
  [43.]
  [25.]]]
0.20839500427246094
[[[ 1.]
  [ 2.]
  [ 3.]]

 [[ 2.]
  [ 3.]
  [ 4.]]

 [[ 3.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [34.]]

 [[ 5.]
  [34.]
  [ 8.]]

 [[34.]
  [ 8.]
  [ 9.]]

 [[ 8.]
  [ 9.]
  [44.]]

 [[ 9.]
  [44.]
  [16.]]

 [[44.]
  [16.]
  [48.]]]
0.043071746826171875
[[[ 2.]
  [ 3.]
  [ 4.]]

 [[ 3.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [11.]]

 [[ 6.]
  [11.]
  [12.]]

 [[11.]
  [12.]
  [14.]]

0.36788177490234375
[[[  1.]
  [  5.]
  [133.]]

 [[  5.]
  [133.]
  [  9.]]

 [[133.]
  [  9.]
  [ 13.]]

 [[  9.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 18.]]

 [[ 14.]
  [ 18.]
  [ 19.]]

 [[ 18.]
  [ 19.]
  [ 21.]]

 [[ 19.]
  [ 21.]
  [ 24.]]

 [[ 21.]
  [ 24.]
  [152.]]

 [[ 24.]
  [152.]
  [154.]]

 [[152.]
  [154.]
  [286.]]

 [[154.]
  [286.]
  [ 32.]]

 [[286.]
  [ 32.]
  [ 43.]]

 [[ 32.]
  [ 43.]
  [ 46.]]

 [[ 43.]
  [ 46.]
  [ 48.]]

 [[ 46.]
  [ 48.]
  [178.]]

 [[ 48.]
  [178.]
  [ 53.]]

 [[178.]
  [ 53.]
  [185.]]

 [[ 53.]
  [185.]
  [ 81.]]

 [[185.]
  [ 81.]
  [ 85.]]

 [[ 81.]
  [ 85.]
  [ 86.]]

 [[ 85.]
  [ 86.]
  [234.]]

 [[ 86.]
  [234.]
  [235.]]]
2.7942657470703125
[[[256.]
  [  1.]
  [  2.]]

 [[  1.]
  [  2.]
  [  4.]]

 [[  2.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [132.]]

 [[  9.]
  [132.]
  [ 12.]]

 [[132.]
  [ 12.]
  [ 14.]]

 [[ 

0.36322021484375
[[[  1.]
  [  2.]
  [103.]]

 [[  2.]
  [103.]
  [295.]]

 [[103.]
  [295.]
  [ 41.]]

 [[295.]
  [ 41.]
  [107.]]

 [[ 41.]
  [107.]
  [155.]]

 [[107.]
  [155.]
  [208.]]

 [[155.]
  [208.]
  [ 17.]]

 [[208.]
  [ 17.]
  [ 83.]]

 [[ 17.]
  [ 83.]
  [213.]]

 [[ 83.]
  [213.]
  [277.]]

 [[213.]
  [277.]
  [119.]]]
1.4636001586914062
[[[64.]
  [65.]
  [36.]]

 [[65.]
  [36.]
  [59.]]

 [[36.]
  [59.]
  [41.]]

 [[59.]
  [41.]
  [75.]]

 [[41.]
  [75.]
  [44.]]

 [[75.]
  [44.]
  [46.]]

 [[44.]
  [46.]
  [15.]]

 [[46.]
  [15.]
  [47.]]

 [[15.]
  [47.]
  [19.]]

 [[47.]
  [19.]
  [21.]]

 [[19.]
  [21.]
  [22.]]

 [[21.]
  [22.]
  [23.]]

 [[22.]
  [23.]
  [24.]]

 [[23.]
  [24.]
  [57.]]

 [[24.]
  [57.]
  [88.]]]
0.5990829467773438
[[[ 0.]
  [ 1.]
  [ 3.]]

 [[ 1.]
  [ 3.]
  [ 4.]]

 [[ 3.]
  [ 4.]
  [ 5.]]

 [[ 4.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [ 9.]]

 [[ 8.]
  [ 9.]
  [11.]]

 [[ 9.]
  [11.]
  [12.]]

 [

0.551239013671875
[[[  1.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [133.]]

 [[  6.]
  [133.]
  [  8.]]

 [[133.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [106.]]

 [[  9.]
  [106.]
  [ 37.]]

 [[106.]
  [ 37.]
  [ 76.]]

 [[ 37.]
  [ 76.]
  [ 45.]]

 [[ 76.]
  [ 45.]
  [ 79.]]

 [[ 45.]
  [ 79.]
  [113.]]]
0.256805419921875
[[[ 4.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 9.]]

 [[ 7.]
  [ 9.]
  [44.]]

 [[ 9.]
  [44.]
  [15.]]

 [[44.]
  [15.]
  [16.]]

 [[15.]
  [16.]
  [19.]]

 [[16.]
  [19.]
  [51.]]

 [[19.]
  [51.]
  [21.]]

 [[51.]
  [21.]
  [23.]]]
0.13822364807128906
[[[  8.]
  [  9.]
  [ 13.]]

 [[  9.]
  [ 13.]
  [ 22.]]

 [[ 13.]
  [ 22.]
  [ 23.]]

 [[ 22.]
  [ 23.]
  [ 28.]]

 [[ 23.]
  [ 28.]
  [ 29.]]

 [[ 28.]
  [ 29.]
  [ 31.]]

 [[ 29.]
  [ 31.]
  [162.]]

 [[ 31.]
  [162.]
  [ 42.]]

 [[162.]
  [ 42.]
  [171.]]

 [[ 42.]
  [171.]
  [ 50.]]

 [[171.]
  [ 50.]
  [ 51.]]

 [[ 50.]
  [ 51.]
  [ 57.]]

 [[ 51.]
  [ 57.]
  [ 59.]]

 [[ 57.]
  [ 59.]

10.882217407226562
[[[  5.]
  [  9.]
  [ 78.]]

 [[  9.]
  [ 78.]
  [ 81.]]

 [[ 78.]
  [ 81.]
  [146.]]

 [[ 81.]
  [146.]
  [ 51.]]

 [[146.]
  [ 51.]
  [ 52.]]

 [[ 51.]
  [ 52.]
  [ 53.]]

 [[ 52.]
  [ 53.]
  [214.]]]
1.4560432434082031
[[[161.]
  [129.]
  [133.]]

 [[129.]
  [133.]
  [105.]]

 [[133.]
  [105.]
  [ 74.]]

 [[105.]
  [ 74.]
  [141.]]

 [[ 74.]
  [141.]
  [ 16.]]

 [[141.]
  [ 16.]
  [ 48.]]

 [[ 16.]
  [ 48.]
  [276.]]

 [[ 48.]
  [276.]
  [ 21.]]

 [[276.]
  [ 21.]
  [ 85.]]

 [[ 21.]
  [ 85.]
  [ 86.]]

 [[ 85.]
  [ 86.]
  [ 55.]]

 [[ 86.]
  [ 55.]
  [ 27.]]

 [[ 55.]
  [ 27.]
  [ 63.]]]
0.08260917663574219
[[[  4.]
  [  7.]
  [  9.]]

 [[  7.]
  [  9.]
  [139.]]

 [[  9.]
  [139.]
  [ 14.]]

 [[139.]
  [ 14.]
  [ 19.]]

 [[ 14.]
  [ 19.]
  [ 22.]]

 [[ 19.]
  [ 22.]
  [ 24.]]]
29.0579833984375
[[[ 1.]
  [ 2.]
  [99.]]

 [[ 2.]
  [99.]
  [ 6.]]

 [[99.]
  [ 6.]
  [38.]]

 [[ 6.]
  [38.]
  [ 8.]]

 [[38.]
  [ 8.]
  [78.]]

 [[ 8.]
  [78.]
  [14.]]

 [[78.]
  [14.]

0.56085205078125
[[[  1.]
  [  3.]
  [  6.]]

 [[  3.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [  8.]]

 [[  7.]
  [  8.]
  [ 12.]]

 [[  8.]
  [ 12.]
  [ 14.]]

 [[ 12.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [207.]]

 [[ 15.]
  [207.]
  [ 17.]]

 [[207.]
  [ 17.]
  [ 19.]]

 [[ 17.]
  [ 19.]
  [ 21.]]

 [[ 19.]
  [ 21.]
  [ 55.]]

 [[ 21.]
  [ 55.]
  [221.]]]
2.586517333984375
[[[  3.]
  [  4.]
  [196.]]

 [[  4.]
  [196.]
  [ 43.]]

 [[196.]
  [ 43.]
  [ 78.]]

 [[ 43.]
  [ 78.]
  [ 79.]]

 [[ 78.]
  [ 79.]
  [ 48.]]

 [[ 79.]
  [ 48.]
  [ 52.]]

 [[ 48.]
  [ 52.]
  [ 55.]]]
0.01226043701171875
[[[ 32.]
  [  1.]
  [  5.]]

 [[  1.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [ 12.]]

 [[  6.]
  [ 12.]
  [ 46.]]

 [[ 12.]
  [ 46.]
  [ 14.]]

 [[ 46.]
  [ 14.]
  [207.]]

 [[ 14.]
  [207.]
  [ 18.]]

 [[207.]
  [ 18.]
  [ 22.]]

 [[ 18.]
  [ 22.]
  [ 87.]]

 [[ 22.]
  [ 87.]
  [ 24.]]

 [[ 87.]
  [ 24.]
  [ 59.]]

 [[ 24.]
  [ 59.]
  [ 29.]]]
20.307476043701172
[[[  1.]
  [ 35.]
  [  4.]]

2.1698150634765625
[[[265.]
  [ 11.]
  [ 12.]]

 [[ 11.]
  [ 12.]
  [ 51.]]

 [[ 12.]
  [ 51.]
  [ 23.]]

 [[ 51.]
  [ 23.]
  [ 57.]]

 [[ 23.]
  [ 57.]
  [124.]]

 [[ 57.]
  [124.]
  [ 93.]]

 [[124.]
  [ 93.]
  [254.]]]
0.017848968505859375
[[[224.]
  [ 65.]
  [  2.]]

 [[ 65.]
  [  2.]
  [  3.]]

 [[  2.]
  [  3.]
  [  4.]]

 [[  3.]
  [  4.]
  [  5.]]

 [[  4.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [ 39.]]

 [[  6.]
  [ 39.]
  [  8.]]

 [[ 39.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 42.]]

 [[  9.]
  [ 42.]
  [ 77.]]

 [[ 42.]
  [ 77.]
  [ 83.]]]
0.13124847412109375
[[[  1.]
  [ 33.]
  [  3.]]

 [[ 33.]
  [  3.]
  [  5.]]

 [[  3.]
  [  5.]
  [  6.]]

 [[  5.]
  [  6.]
  [  7.]]

 [[  6.]
  [  7.]
  [299.]]

 [[  7.]
  [299.]
  [203.]]

 [[299.]
  [203.]
  [ 13.]]

 [[203.]
  [ 13.]
  [205.]]

 [[ 13.]
  [205.]
  [245.]]

 [[205.]
  [245.]
  [151.]]

 [[245.]
  [151.]
  [ 58.]]]
3.837657928466797
[[[161.]
  [ 97.]
  [ 65.]]

 [[ 97.]
  [ 65.]
  [ 98.]]

 [[ 65.]
  [ 98.]
  [  

0.15375137329101562
[[[  1.]
  [  5.]
  [  7.]]

 [[  5.]
  [  7.]
  [  9.]]

 [[  7.]
  [  9.]
  [ 12.]]

 [[  9.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 15.]]

 [[ 14.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 17.]]

 [[ 16.]
  [ 17.]
  [ 18.]]

 [[ 17.]
  [ 18.]
  [ 19.]]

 [[ 18.]
  [ 19.]
  [ 21.]]

 [[ 19.]
  [ 21.]
  [152.]]

 [[ 21.]
  [152.]
  [ 24.]]

 [[152.]
  [ 24.]
  [ 37.]]

 [[ 24.]
  [ 37.]
  [ 61.]]

 [[ 37.]
  [ 61.]
  [ 65.]]

 [[ 61.]
  [ 65.]
  [215.]]

 [[ 65.]
  [215.]
  [ 94.]]

 [[215.]
  [ 94.]
  [ 97.]]

 [[ 94.]
  [ 97.]
  [107.]]

 [[ 97.]
  [107.]
  [113.]]]
4.1212005615234375
[[[  1.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 11.]]

 [[  9.]
  [ 11.]
  [ 12.]]

 [[ 11.]
  [ 12.]
  [ 13.]]

 [[ 12.]
  [ 13.]
  [ 15.]]

 [[ 13.]
  [ 15.]
  [ 16.]]

 [[ 15.]
  [ 16.]
  [ 17.]]

 [[ 16.]
  [ 17.]
  [ 18.]]

 [[ 17.]
  [ 18.]
  [178.]]

 [[ 18.]
  [178.]
  [ 21.]]]
0.9169559478759766
[[[129.]
  [101.]
  [ 75.]]

 [[101.]
  [ 7

0.3911399841308594
[[[  1.]
  [162.]
  [  4.]]

 [[162.]
  [  4.]
  [  6.]]

 [[  4.]
  [  6.]
  [  8.]]

 [[  6.]
  [  8.]
  [  9.]]

 [[  8.]
  [  9.]
  [ 42.]]

 [[  9.]
  [ 42.]
  [106.]]

 [[ 42.]
  [106.]
  [105.]]

 [[106.]
  [105.]
  [ 13.]]

 [[105.]
  [ 13.]
  [ 18.]]

 [[ 13.]
  [ 18.]
  [182.]]

 [[ 18.]
  [182.]
  [184.]]

 [[182.]
  [184.]
  [153.]]]
0.0718231201171875
[[[  3.]
  [  7.]
  [231.]]

 [[  7.]
  [231.]
  [ 13.]]

 [[231.]
  [ 13.]
  [ 14.]]

 [[ 13.]
  [ 14.]
  [ 16.]]

 [[ 14.]
  [ 16.]
  [208.]]

 [[ 16.]
  [208.]
  [214.]]]
1.4919204711914062
[[[ 2.]
  [ 3.]
  [36.]]

 [[ 3.]
  [36.]
  [ 6.]]

 [[36.]
  [ 6.]
  [16.]]

 [[ 6.]
  [16.]
  [23.]]

 [[16.]
  [23.]
  [24.]]

 [[23.]
  [24.]
  [57.]]

 [[24.]
  [57.]
  [28.]]]
0.006439208984375
[[[ 2.]
  [ 5.]
  [ 6.]]

 [[ 5.]
  [ 6.]
  [ 7.]]

 [[ 6.]
  [ 7.]
  [ 8.]]

 [[ 7.]
  [ 8.]
  [12.]]

 [[ 8.]
  [12.]
  [13.]]

 [[12.]
  [13.]
  [14.]]

 [[13.]
  [14.]
  [18.]]

 [[14.]
  [18.]
  [19.]]

 [[18.]
  [19

KeyboardInterrupt: 

In [4]:
data = pd.read_csv("~/PycharmProjects/Diabetes/final.csv", sep=',')

Albumin_Creatinine_data = data[['Patient_ID', 'PerformedDate', 'Albumin/Creatinine_Res']]
Albumin_Creatinine_data = Albumin_Creatinine_data.dropna()
Albumin_Creatinine_data = Albumin_Creatinine_data.sort_values(by='PerformedDate', ascending=True)

grouped_patients = Albumin_Creatinine_data.groupby("Patient_ID")
grouped_lists = grouped_patients["Albumin/Creatinine_Res"].apply(list)
grouped_lists = grouped_lists.reset_index()
grouped_lists['Albumin/Creatinine_Res'] = grouped_lists['Albumin/Creatinine_Res'].apply(lambda x: list(set(x)))
data = grouped_lists[['Albumin/Creatinine_Res']]

def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence) - 1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

for index, row in data.iterrows() :
    raw_seq = data['Albumin/Creatinine_Res'].at[index]
    if len(data['Albumin/Creatinine_Res'].at[index]) > 8 :
        n_steps = 3
# split into samples
        X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
        n_features = 1
        X = X.reshape((X.shape[0], X.shape[1], n_features))
        x_input = np.asarray(raw_seq[-4:-1])
        x_input = x_input.reshape((1, n_steps, n_features))
        y_actual = np.asarray(raw_seq[-1:])
    else :
        continue

In [ ]:
data = pd.read_csv("~/PycharmProjects/Diabetes/final.csv", sep=',')

Albumin_Creatinine_data = data[['Patient_ID', 'PerformedDate', 'Albumin/Creatinine_Res']]
Albumin_Creatinine_data = Albumin_Creatinine_data.dropna()
Albumin_Creatinine_data = Albumin_Creatinine_data[Albumin_Creatinine_data['Albumin/Creatinine_Res'] < 300]
Albumin_Creatinine_data = Albumin_Creatinine_data.sort_values(by='PerformedDate', ascending=True)
print(Albumin_Creatinine_data)

In [ ]:
data = pd.read_csv("~/PycharmProjects/Diabetes/final.csv", sep=',')

Albumin_Creatinine_data = data[['Patient_ID', 'PerformedDate', 'Albumin/Creatinine_Res']]
Albumin_Creatinine_data = Albumin_Creatinine_data.dropna()
Albumin_Creatinine_data = Albumin_Creatinine_data[Albumin_Creatinine_data['Albumin/Creatinine_Res'] < 300]
Albumin_Creatinine_data = Albumin_Creatinine_data.sort_values(by='PerformedDate', ascending=True)

grouped_patients = Albumin_Creatinine_data.groupby("Patient_ID")
grouped_lists = grouped_patients["Albumin/Creatinine_Res"].apply(list)
grouped_lists = grouped_lists.reset_index()
grouped_lists['Albumin/Creatinine_Res'] = grouped_lists['Albumin/Creatinine_Res'].apply(lambda x: list(set(x)))

data = grouped_lists[['Albumin/Creatinine_Res']]

def split_sequence(sequence, n_steps):
    X, y = list(), list()
    for i in range(len(sequence)):
        # find the end of this pattern
        end_ix = i + n_steps
        # check if we are beyond the sequence
        if end_ix > len(sequence) - 1:
            break
        # gather input and output parts of the pattern
        seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return array(X), array(y)

a = [0,0,0]
b = [[0], [0], [0], [0], [0], [0], [0], [0], [0], [0]]
for index, row in data.iterrows() :
    #raw_seq = data['Albumin/Creatinine_Res'].at[index]
    if len(data['Albumin/Creatinine_Res'].at[index]) > 8 :
        seq = data['Albumin/Creatinine_Res'].at[index]
        # choose a number of time steps
        n_steps = 3
        # split into samples
        X, y = split_sequence(seq, n_steps)
        y = y.reshape((-1, 1))
        a = np.vstack((a, X))
        b = np.vstack((b, y))
    else:
        continue
X = np.delete(a, (0), axis=0)
y = b[10:, :]
print(y)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')
# fit model
model.fit(X, y, epochs=200, verbose=0)

for index, row in data.iterrows() :
# demonstrate prediction
        x_input = np.asarray(seq[-4:-1])
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat)
        y_actual = np.asarray(seq[-1:])
        rms = sqrt(mean_squared_error(y_actual, yhat))
        print(rms)